<?php
$this->headTitle('Revisar Proveedor');

$this->mainMenu()->setActiveItemId('suppliers');

$this->pageBreadcrumbs()->setItems([
            'Home' => $this->url('home'),
            'Proveedores' => $this->url('suppliers'),
            'Revisar' => $this->url('suppliers', ['action' => 'view', 'id' => $supplier->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h2>Revisar <?= $this->escapeHtml($supplier->getName()) ?></h2>

<p>
    <a class="btn btn-default" href="<?= $this->url(
        'suppliers',
        ['action' => 'edit', 'id' => $supplier->getId()]
    ); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Actualizar
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Folio:</th>
                <td><?= $this->escapeHtml($supplier->getId()) ?></th>
            </tr>
            <tr>
                <th>Categoría:</th>
                <td><?= $this->escapeHtml($supplier->getCategoriesAsString()) ?></th>
            </tr>
            <tr>
                <th>Nombre:</th>
                <td><?= $this->escapeHtml($supplier->getName()) ?></th>
            </tr>
            <tr>
                <th>Dirección:</th>
                <td><?= $this->escapeHtml($supplier->getTaxAddress()) ?></th>
            </tr>
            <tr>
                <th>R.F.C.:</th>
                <td><?= $this->escapeHtml($supplier->getRfc()) ?></th>
            </tr>
            <tr>
                <th>Cuentas Bancarias</th>
                <td>
                    <?php foreach ($supplier->getBankAccounts() as $bankAccount) :
                        $bankAccountString = $bankAccount->getBank();
                        $bankAccountString .= ' (' . $bankAccount->getCurrency()->getCode() . ')';
                        $bankAccountString .= ' ' . $bankAccount->getNumber();
                        $bankAccountString .= ' (CLABE: ' . $bankAccount->getClabe() . ')<br>';
                        ?>
                    <?= $this->escapeHtml($bankAccountString) ?>
                    <?php endforeach; ?>
                </td>
            </tr>
            <tr>
                <th>Condiciones de Pago:</th>
                <td><?= $this->escapeHtml($supplier->getPaymentTerms()) ?></th>
            </tr>
            <tr>
                <th>Limite de Crédito:</th>
                <td><?= $this->escapeHtml(
                    $this->currencyFormat($supplier->getCreditLimit(), 'MXN', true, 'es_MX')
                ) ?></th>
            </tr>
            <tr>
                <th>Descuento:</th>
                <td><?= $this->escapeHtml(
                    $this->numberFormat(
                        $supplier->getDiscount(),
                        NumberFormatter::PERCENT,
                        NumberFormatter::TYPE_DEFAULT,
                        'es_MX'
                    )
                ) ?></th>
            </tr>
            <tr>
                <th>Tiempo de Entrega:</th>
                <td><?= $this->escapeHtml($supplier->getDeliveryTime()) ?></th>
            </tr>
            <tr>
                <th>Observaciones:</th>
                <td><?= $this->escapeHtml($supplier->getComments()) ?></th>
            </tr>
        </table>
    </div>
</div>