<?php
$this->headTitle('Actualizar Unidad de Medida');

$this->mainMenu()->setACtiveItemId('measureUnits');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Unidades de Medida' => $this->url('measureUnits'),
    'Actualizar' => $this->url('measureUnits', ['action' => 'edit'])
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Kilogramo'
]);

$form->get('code')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Kg',
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Descripción de la unidad de medida.'
]);

$form->get('submit')->setAttributes([
    'value' => 'Actualizar',
    'class' => 'btn btn-primary'
]);

$form->prepare();

?>

<h2>Actualizar <i><?= $this->escapeHtml($measureUnit->getName()); ?></i></h2>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('code')); ?>
            <?= $this->formElement($form->get('code')); ?>
            <?= $this->formElementErrors($form->get('code')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>

        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>
</div>