<?php
$this->headTitle('Agregar Categoría');

$this->mainMenu()->setActiveItemId('categories');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Categorias' => $this->url('categories'),
    'Agregar' => $this->url('categories', ['action' => 'add'])
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Tornillos'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Descripción de la categoría.'
]);

$form->get('submit')->setAttributes([
    'value' => 'Crear',
    'class' => 'btn btn-primary'
]);

$form->prepare();

?>

<h2>Agregar Categoría</h2>

<p>
    Llene los siguientes campos y presione <i>Crear</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>

        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>
</div>