<?php
$this->headTitle('Revisar Categoría');

$this->mainMenu()->setActiveItemId('categories');

$this->pageBreadcrumbs()->setItems([
            'Home' => $this->url('home'),
            'Categorias' => $this->url('categories'),
            'Revisar' => $this->url('categories', ['action' => 'view', 'id' => $category->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h2>Revisar <?= $this->escapeHtml($category->getName()) ?></h2>

<p>
    <a class="btn btn-default" href="<?= $this->url(
        'categories',
        ['action' => 'edit', 'id' => $category->getId()]
    ); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Actualizar
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($category->getId()) ?></th>
            </tr>
            <tr>
                <th>Nombre:</th>
                <td><?= $this->escapeHtml($category->getName()) ?></th>
            </tr>
            <tr>
                <th>Descripción:</th>
                <td><?= $this->escapeHtml($category->getDescription()) ?></th>
            </tr>
        </table>
    </div>
</div>