<?php
$this->headTitle('Actualizar Grupo de Artículos');

$this->mainMenu()->setActiveItemId('classifications');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Grupos de Artículos' => $this->url('classifications'),
    'Actualizar' => $this->url('classifications', ['action' => 'edit']),
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'RELEVADORES'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Descripción del grupo de artículos'
]);

$form->get('submit')->setAttributes([
    'value' => 'Actualizar',
    'class' => 'btn btn-primary'
]);

$form->prepare();
?>

<h2>Actualizar <i><?= $this->escapeHtml($classification->getName()); ?></i></h2>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>