<?php
$this->headTitle('Clientes');

$this->mainMenu()->setActiveItemId('clients');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Clientes' => $this->url('clients'),
]);
?>

<h2>Clientes</h2>
<p>
    <a class="btn btn-default" href="
        <?= $this->url('clients', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar
    </a>
</p>

<table class="table table-striped">
    <tr>
        <th>Folio</th>
        <th>Nombre</th>
        <th>Datos Fiscales</th>
        <th>Contacto</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($clients as $client) : ?>
    <tr>
        <td><?= $this->escapeHtml($client->getId()); ?></td>
        <td><a href="<?= $this->url('clients', ['action' => 'view', 'id' => $client->getId()]); ?>">
                <?= $this->escapeHtml($client->getName()); ?>
            </a>
        </td>
        <td><?php
        $taxData = '';
        if ($client->getTaxAddress()) {
            $taxData = 'Dirección: ' . $client->getTaxAddress();
        }
        if ($taxData != '') {
            $taxData .= '<br>';
        }
        if ($client->getRfc()) {
            $taxData .= 'R.F.C.: ' . $client->getRfc();
        }
        echo $taxData;
        ?></td>
        <td>&nbsp;</td>
        <td>
            <a class="btn btn-warning" 
                href="<?=
                    $this->url(
                        'clients',
                        ['action' => 'edit', 'id' => $client->getId()]
                    );
                ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Actualizar
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>