<?php
$this->headLink()->appendStylesheet('/css/modal.css');
$this->inlineScript()->appendFile('/js/modal.js', 'text/javascript');
$this->headTitle('Revisar Componente');

$this->mainMenu()->setActiveItemId('components');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Componentes' => $this->url('components'),
    'Revisar' => $this->url('components', ['action' => 'view', 'id' => $component->getId()]),
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h2>Detalles de <?= $this->escapeHtml($component->getFolio()) ?></h2>

<p>
    <a class="btn btn-default" href="
        <?= $this->url(
            'components',
            ['action' => 'edit', 'id' => $component->getId()]
        );
        ?>">
        <span class="glyphicon glyphicon-pencil"></span> Actualizar
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Folio</th>
                <td><?= $this->escapeHtml($component->getFolio()) ?></td>
            </tr>
            <tr>
                <th>Función</th>
                <td><?= $this->escapeHtml($component->getFunction()) ?></td>
            </tr>
            <tr>
                <th>Descripción</th>
                <td><?= $this->escapeHtml($component->getDescription()) ?></td>
            </tr>
            <tr>
                <th>Catálogo</th>
                <td><?= $this->escapeHtml($component->getListCode()) ?></td>
            </tr>
            <tr>
                <th>Tipo de Compra</th>
                <td><?= $this->escapeHtml($component->getPurchaseTypeAsString()) ?></td>
            </tr>
            <tr>
                <th>Proveedor</th>
                <td><?= $this->escapeHtml($component->getSupplier()->getName()) ?></td>
            </tr>
            <tr>
                <th>Marca</th>
                <td><?= $this->escapeHtml($component->getBrand()->getName()) ?></td>
            </tr>
            <tr>
                <th>Grupo de Artículos</th>
                <td><?= $this->escapeHtml($component->getClassification()->getName()) ?></td>
            </tr>
            <tr>
                <th>Unidad de Compra</th>
                <td><?= $this->escapeHtml($component->getPurchaseUnit()->getName()) ?></td>
            </tr>
            <tr>
                <th>Unidad de Inventario</th>
                <td><?= $this->escapeHtml($component->getInventoryUnit()->getName()) ?></td>
            </tr>
            <tr>
                <th>Presentación</th>
                <td><?= $this->escapeHtml($component->getPresentation()) ?></td>
            </tr>
            <tr>
                <th>Cantidad por Presentatión</th>
                <td><?= $this->escapeHtml($component->getAmountPresentation()) ?></td>
            </tr>
            <tr>
                <th>Precio de Compra Unitario</th>
                <td><?= $this->escapeHtml($component->getUnitPricePurchase()) ?></td>
            </tr>
            <tr>
                <th>Precio de Compra por Presentación</th>
                <td><?= $this->escapeHtml($component->getPresentationPurchasePrice()) ?></td>
            </tr>
            <tr>
                <th>Precio de Venta Unitario</th>
                <td><?= $this->escapeHtml($component->getSaleUnitPrice()) ?></td>
            </tr>
            <tr>
                <th>Precio de Venta Total</th>
                <td><?= $this->escapeHtml($component->getSaleTotalPrice()) ?></td>
            </tr>
            <tr>
                <th>Precio de Compra Unitario de Importación</th>
                <td><?= $this->escapeHtml($component->getUnitPriceImportPurchase()) ?></td>
            </tr>
            <tr>
                <th>Precio de Venta de Importación</th>
                <td><?= $this->escapeHtml($component->getImportSalePrice()) ?></td>
            </tr>
            <tr>
                <th>Moneda</th>
                <td><?= $this->escapeHtml($component->getCurrency()->getCode()) ?></td>
            </tr>
            <tr>
                <th>Tiempo de Entrega del Proveedor</th>
                <td><?= $this->escapeHtml($component->getSupplierDeliveryTime()) ?></td>
            </tr>
            <tr>
                <th>Clave SAT del Artículo</th>
                <td><?= $this->escapeHtml($component->getSatCode()) ?></td>
            </tr>
        </table>
    </div>
    <div class="col-md-6" align="center">
        <div class="row">
            <div class="img-thumbnail">
                    
            <img id="myImg" src="<?= $this->url('components', ['action' => 'image'], 
                    ['query' => ['name' => $component->getImageFile(), 'thumbnail' => true]]); ?>"
                    style="width:100%;max-width:300px">
                    
            </div>
        </div>
        <div class="row">
            <div class="img-thumbnail">
                <a target="_blank" href="<?= $this->url('components', ['action' => 'datasheet'], 
                    ['query' => ['name' => $component->getDatasheetFile()]]); ?>">
                    <img src="<?= $this->url('components', ['action' => 'datasheet'], 
                        ['query' => ['name' => $component->getDatasheetFile(), 'thumbnail' => true]]); ?>" alt="">
                </a>
            </div>
        </div>
    </div>
</div>

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- The Close Button -->
  <span class="close">&times;</span>

  <!-- Modal Content (The Image) -->
  <img class="modal-content" id="img01">

  <!-- Modal Caption (Image Text) -->
  <div id="caption"></div>
</div>
